import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Navbar
    logout: 'Logout',
    guest: 'Guest',
    
    // Hero
    heroSubtitle: 'Explore the World with Confidence',
    heroTitle: 'Discover Your Next',
    heroTitleGradient: 'Adventure',
    heroDescription: 'Book unforgettable tours to the world\'s most amazing destinations. Curated experiences, expert guides, and memories that last forever.',
    exploreTours: 'Explore Tours',
    watchVideo: 'Watch Video',
    destinations: 'Destinations',
    happyTravelers: 'Happy Travelers',
    averageRating: 'Average Rating',
    heroBadge: 'Your Dream Vacation Awaits',
    heroMainTitle: 'Explore The World With',
    heroSearchPlaceholder: 'Where do you want to go? (e.g., Paris, Bali, Dubai...)',
    searchBtn: 'Search',
    popular: 'Popular',
    tourPackages: 'Tour Packages',
    rating: 'Rating',
    scrollToExplore: 'Scroll to explore',
    
    // Categories
    browseByCategory: 'Browse By Category',
    chooseTravelStyle: 'Choose Your Travel Style',
    findPerfectPackage: 'Find the perfect tour package that matches your travel preferences',
    packages: 'Packages',
    catInternational: 'International Tours',
    catInternationalDesc: 'Explore destinations worldwide',
    catDomestic: 'Domestic Tours',
    catDomesticDesc: 'Discover incredible India',
    catHoneymoon: 'Honeymoon Packages',
    catHoneymoonDesc: 'Romantic getaways for couples',
    catAdventure: 'Adventure Tours',
    catAdventureDesc: 'Thrilling experiences await',
    catBeach: 'Beach Holidays',
    catBeachDesc: 'Sun, sand and sea',
    catPilgrimage: 'Pilgrimage Tours',
    catPilgrimageDesc: 'Spiritual journeys',
    
  // Navbar / common
  home: 'Home',
  categoriesNav: 'Categories',
  toursNav: 'Tours',
  aboutNav: 'About',
  contactNav: 'Contact',
  brandName: 'Tour Explorer',
  brandTagline: 'Your Travel Partner',
  phoneContact: '📞 +91 90809 01058',
  quickLinks: 'Quick Links',
  popularDestinationsTitle: 'Popular Destinations',
  contactInfoTitle: 'Contact Info',
    
    // Features
    whyChooseUs: 'Why Choose Us',
    featuresTitle: 'Everything you need for the perfect trip',
    featuresSubtitle: 'We provide comprehensive travel solutions to make your journey seamless and memorable',
    curatedExperiences: 'Curated Experiences',
    curatedDesc: 'Hand-picked tours designed by travel experts for unforgettable adventures.',
    bestPrice: 'Best Price Guarantee',
    bestPriceDesc: 'Get the best deals with our price match guarantee and exclusive offers.',
    secureBooking: 'Secure Booking',
    secureBookingDesc: 'Book with confidence using our secure payment system and instant confirmation.',
    support247: '24/7 Support',
    supportDesc: 'Our dedicated team is always here to help you before, during, and after your trip.',
    
    // Features Section
    whyTourExplorer: 'Why Tour Explorer',
    whyTravelWithUs: 'Why Travel With Us?',
    travelDreamsComeTrue: 'We make your travel dreams come true with our exceptional services',
    featBestPrice: 'Best Price Guarantee',
    featBestPriceDesc: 'We offer competitive prices and price match guarantee on all tour packages.',
    featSafe: 'Safe & Secure',
    featSafeDesc: 'Your safety is our priority. All tours are fully insured and vetted.',
    featHandpicked: 'Handpicked Tours',
    featHandpickedDesc: 'Every destination is carefully selected by our travel experts.',
    featSupport: '24/7 Support',
    featSupportDesc: 'Round-the-clock customer support before, during, and after your trip.',
    featEasyBooking: 'Easy Booking',
    featEasyBookingDesc: 'Simple and hassle-free booking process with instant confirmation.',
    featTrusted: 'Trusted Reviews',
    featTrustedDesc: '10,000+ happy travelers with 4.9 average rating.',
    testimonials: 'Testimonials',
    whatTravelersSay: 'What Our Travelers Say',
    testimonial1: 'Amazing experience! The Bali trip was perfectly organized. Every detail was taken care of.',
    testimonial2: 'Best travel agency! Our honeymoon in Maldives was a dream come true. Highly recommended!',
    testimonial3: 'Professional service and great value for money. The Europe tour exceeded our expectations.',
    
    // Tours Section
    popularTours: 'Popular Tours',
    exploreBest: 'Explore Our Best Destinations',
    handPicked: 'Hand-picked tours to the world\'s most incredible places',
    searchPlaceholder: 'Search tours by name or location...',
    allTours: 'All Tours',
    priceLowToHigh: 'Price: Low to High',
    priceHighToLow: 'Price: High to Low',
    highestRated: 'Highest Rated',
    duration: 'Duration',
    noResults: 'No tours found. Try a different search.',
    seeMore: 'See More Tours',
    seeLess: 'See Less',
    
    // Tour Card
    from: 'From',
    max: 'Max',
    bookNow: 'Book Now',
    
    // Booking Modal
    book: 'Book',
    total: 'Total',
    fullName: 'Full Name',
    email: 'Email',
    phone: 'Phone',
    tourDate: 'Tour Date',
    numberOfGuests: 'Number of Guests',
    confirmBooking: 'Confirm Booking',
    
    // Auth
    welcomeBack: 'Welcome Back',
    signInContinue: 'Sign in to continue your journey',
    password: 'Password',
    signIn: 'Sign In',
    dontHaveAccount: 'Don\'t have an account?',
    signUp: 'Sign Up',
    joinTourExplorer: 'Join Tour Explorer',
    createAccount: 'Create an account to start your adventure',
    confirmPassword: 'Confirm Password',
    alreadyHaveAccount: 'Already have an account?',
    createAccountBtn: 'Create Account',
    
    // Messages
    loginRequired: 'Please login to book a tour',
    bookingConfirmed: 'Booking confirmed!',
    bookingFailed: 'Failed to create booking. Please try again.',
    loadingTours: 'Loading amazing tours...',
    failedToLoad: 'Failed to load tours. Please try again later.',
    retry: 'Retry',
    
    // Tour Details Modal
    aboutThisTour: 'About This Tour',
    highlights: 'Highlights',
    
    // Contact Section
    getInTouch: 'Get In Touch',
    planDreamVacation: 'Plan Your Dream Vacation',
    contactHelpText: 'Have questions or need help planning your trip? Our travel experts are here to assist you 24/7.',
    visitUs: 'Visit Us',
    callUs: 'Call Us',
    emailUs: 'Email Us',
    workingHours: 'Working Hours',
    supportAvailable: '24/7 Support Available',
    sendEnquiry: 'Send Us An Enquiry',
    yourName: 'Your Name',
    enterName: 'Enter your name',
    phoneNumber: 'Phone Number',
    emailAddress: 'Email Address',
    enterEmail: 'your@email.com',
    preferredDestination: 'Preferred Destination',
    selectDestination: 'Select Destination',
    other: 'Other',
    yourMessage: 'Your Message',
    tellTravelPlans: 'Tell us about your travel plans...',
    sending: 'Sending...',
    sendEnquiryBtn: 'Send Enquiry ✈️',
    enquirySuccess: '✅ Thank you for your enquiry! Our team will contact you within 24 hours.',
    enquiryFailed: '❌ Failed to submit enquiry. Please try again.',
    
    // Settings
    settings: 'Settings',
    languageCurrency: 'Language & Currency',
    language: 'Language',
    currency: 'Currency',
    displaySettings: 'Display Settings',
    theme: 'Theme',
    dark: 'Dark',
    light: 'Light',
    auto: 'Auto (System)',
    fontSize: 'Font Size',
    small: 'Small',
    medium: 'Medium',
    large: 'Large',
    showPrices: 'Show Prices',
    bookingLimitations: 'Booking Limitations',
    maxGuests: 'Max Guests Per Booking',
    advanceBooking: 'Advance Booking (Days)',
    minNotice: 'Minimum Notice (Days)',
    searchPreferences: 'Search Preferences',
    defaultSort: 'Default Sort',
    priceRangeMin: 'Min Price',
    priceRangeMax: 'Max Price',
    showOnlyAvailable: 'Show Only Available Tours',
    notifications: 'Notifications',
    emailNotifications: 'Email Notifications',
    smsNotifications: 'SMS Notifications',
    promotionalEmails: 'Promotional Emails',
    bookingReminders: 'Booking Reminders',
    privacy: 'Privacy',
    shareData: 'Share Usage Data',
    locationAccess: 'Location Access',
    resetDefaults: 'Reset to Defaults',
    done: 'Done',
    settingsReset: 'Settings reset to default!',
  },
  hi: {
    // Navbar
    logout: 'लॉग आउट',
    guest: 'अतिथि',
    
    // Hero
    heroSubtitle: 'आत्मविश्वास के साथ दुनिया का अन्वेषण करें',
    heroTitle: 'अपना अगला खोजें',
    heroTitleGradient: 'रोमांच',
    heroDescription: 'दुनिया के सबसे अद्भुत गंतव्यों के लिए अविस्मरणीय यात्राएं बुक करें। क्यूरेटेड अनुभव, विशेषज्ञ गाइड, और यादें जो हमेशा के लिए रहती हैं।',
    exploreTours: 'टूर देखें',
    watchVideo: 'वीडियो देखें',
    destinations: 'गंतव्य',
    happyTravelers: 'खुश यात्री',
    averageRating: 'औसत रेटिंग',
    heroBadge: 'आपकी सपनों की छुट्टी आपका इंतजार कर रही है',
    heroMainTitle: 'दुनिया का अन्वेषण करें',
    heroSearchPlaceholder: 'आप कहाँ जाना चाहते हैं? (जैसे, पेरिस, बाली, दुबई...)',
    searchBtn: 'खोजें',
    popular: 'लोकप्रिय',
    tourPackages: 'टूर पैकेज',
    rating: 'रेटिंग',
    scrollToExplore: 'अन्वेषण के लिए स्क्रॉल करें',
    
    // Categories
    browseByCategory: 'श्रेणी के अनुसार ब्राउज़ करें',
    chooseTravelStyle: 'अपनी यात्रा शैली चुनें',
    findPerfectPackage: 'अपनी यात्रा प्राथमिकताओं से मेल खाने वाला सही टूर पैकेज खोजें',
    packages: 'पैकेज',
    catInternational: 'अंतर्राष्ट्रीय टूर',
    catInternationalDesc: 'दुनिया भर के गंतव्यों का अन्वेषण करें',
    catDomestic: 'घरेलू टूर',
    catDomesticDesc: 'अविश्वसनीय भारत की खोज करें',
    catHoneymoon: 'हनीमून पैकेज',
    catHoneymoonDesc: 'जोड़ों के लिए रोमांटिक गेटवे',
    catAdventure: 'एडवेंचर टूर',
    catAdventureDesc: 'रोमांचक अनुभव आपका इंतजार कर रहे हैं',
    catBeach: 'बीच हॉलिडे',
    catBeachDesc: 'धूप, रेत और समुद्र',
    catPilgrimage: 'तीर्थ यात्रा टूर',
    catPilgrimageDesc: 'आध्यात्मिक यात्राएं',
    
    // Features
    whyChooseUs: 'हमें क्यों चुनें',
    featuresTitle: 'सही यात्रा के लिए आपको जो कुछ भी चाहिए',
    featuresSubtitle: 'हम आपकी यात्रा को सहज और यादगार बनाने के लिए व्यापक यात्रा समाधान प्रदान करते हैं',
    curatedExperiences: 'क्यूरेटेड अनुभव',
    curatedDesc: 'अविस्मरणीय रोमांच के लिए यात्रा विशेषज्ञों द्वारा डिज़ाइन किए गए हाथ से चुने गए टूर।',
    bestPrice: 'सर्वोत्तम मूल्य गारंटी',
    bestPriceDesc: 'हमारी मूल्य मिलान गारंटी और विशेष ऑफ़र के साथ सर्वोत्तम सौदे प्राप्त करें।',
    secureBooking: 'सुरक्षित बुकिंग',
    secureBookingDesc: 'हमारे सुरक्षित भुगतान सिस्टम और तत्काल पुष्टि का उपयोग करके आत्मविश्वास के साथ बुक करें।',
    support247: '24/7 सहायता',
    supportDesc: 'हमारी समर्पित टीम आपकी यात्रा से पहले, दौरान और बाद में हमेशा आपकी मदद के लिए यहां है।',
    
    // Features Section
    whyTourExplorer: 'टूर एक्सप्लोरर क्यों',
    whyTravelWithUs: 'हमारे साथ यात्रा क्यों करें?',
    travelDreamsComeTrue: 'हम अपनी असाधारण सेवाओं के साथ आपके यात्रा सपनों को साकार करते हैं',
    featBestPrice: 'सर्वोत्तम मूल्य गारंटी',
    featBestPriceDesc: 'हम सभी टूर पैकेजों पर प्रतिस्पर्धी मूल्य और मूल्य मिलान गारंटी प्रदान करते हैं।',
    featSafe: 'सुरक्षित और संरक्षित',
    featSafeDesc: 'आपकी सुरक्षा हमारी प्राथमिकता है। सभी टूर पूरी तरह से बीमित और सत्यापित हैं।',
    featHandpicked: 'हाथ से चुने गए टूर',
    featHandpickedDesc: 'हर गंतव्य हमारे यात्रा विशेषज्ञों द्वारा सावधानीपूर्वक चुना गया है।',
    featSupport: '24/7 सहायता',
    featSupportDesc: 'आपकी यात्रा से पहले, दौरान और बाद में चौबीसों घंटे ग्राहक सहायता।',
    featEasyBooking: 'आसान बुकिंग',
    featEasyBookingDesc: 'तत्काल पुष्टि के साथ सरल और परेशानी मुक्त बुकिंग प्रक्रिया।',
    featTrusted: 'विश्वसनीय समीक्षाएं',
    featTrustedDesc: '4.9 औसत रेटिंग के साथ 10,000+ खुश यात्री।',
    testimonials: 'प्रशंसापत्र',
    whatTravelersSay: 'हमारे यात्री क्या कहते हैं',
    testimonial1: 'अद्भुत अनुभव! बाली यात्रा पूरी तरह से व्यवस्थित थी। हर विवरण का ध्यान रखा गया।',
    testimonial2: 'सबसे अच्छी ट्रैवल एजेंसी! मालदीव में हमारा हनीमून एक सपना सच हो गया। अत्यधिक अनुशंसित!',
    testimonial3: 'पेशेवर सेवा और पैसे का बढ़िया मूल्य। यूरोप टूर ने हमारी उम्मीदों से बढ़कर प्रदर्शन किया।',
    
    // Tours Section
    popularTours: 'लोकप्रिय टूर',
    exploreBest: 'हमारे सर्वश्रेष्ठ गंतव्यों का अन्वेषण करें',
    handPicked: 'दुनिया के सबसे अविश्वसनीय स्थानों के लिए हाथ से चुने गए टूर',
    searchPlaceholder: 'नाम या स्थान से टूर खोजें...',
    allTours: 'सभी टूर',
    priceLowToHigh: 'मूल्य: कम से अधिक',
    priceHighToLow: 'मूल्य: अधिक से कम',
    highestRated: 'उच्चतम रेटेड',
    duration: 'अवधि',
    noResults: 'कोई टूर नहीं मिला। एक अलग खोज का प्रयास करें।',
    seeMore: 'और टूर देखें',
    seeLess: 'कम देखें',
    
    // Tour Card
    from: 'से',
    max: 'अधिकतम',
    bookNow: 'अभी बुक करें',
    
    // Booking Modal
    book: 'बुक करें',
    total: 'कुल',
    fullName: 'पूरा नाम',
    email: 'ईमेल',
    phone: 'फोन',
    tourDate: 'टूर की तारीख',
    numberOfGuests: 'मेहमानों की संख्या',
    confirmBooking: 'बुकिंग की पुष्टि करें',
    
    // Auth
    welcomeBack: 'वापसी पर स्वागत है',
    signInContinue: 'अपनी यात्रा जारी रखने के लिए साइन इन करें',
    password: 'पासवर्ड',
    signIn: 'साइन इन करें',
    dontHaveAccount: 'खाता नहीं है?',
    signUp: 'साइन अप करें',
    joinTourExplorer: 'टूर एक्सप्लोरर में शामिल हों',
    createAccount: 'अपना रोमांच शुरू करने के लिए एक खाता बनाएं',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    alreadyHaveAccount: 'पहले से खाता है?',
    createAccountBtn: 'खाता बनाएं',
    
    // Messages
    loginRequired: 'टूर बुक करने के लिए कृपया लॉगिन करें',
    bookingConfirmed: 'बुकिंग की पुष्टि हो गई!',
    bookingFailed: 'बुकिंग बनाने में विफल। कृपया पुनः प्रयास करें।',
    loadingTours: 'अद्भुत टूर लोड हो रहे हैं...',
    failedToLoad: 'टूर लोड करने में विफल। कृपया बाद में पुनः प्रयास करें।',
    retry: 'पुनः प्रयास करें',
    
    // Tour Details Modal
    aboutThisTour: 'इस टूर के बारे में',
    highlights: 'मुख्य आकर्षण',
    
    // Contact Section
    getInTouch: 'संपर्क करें',
    planDreamVacation: 'अपनी सपनों की छुट्टी की योजना बनाएं',
    contactHelpText: 'कोई सवाल है या अपनी यात्रा की योजना बनाने में मदद चाहिए? हमारे यात्रा विशेषज्ञ 24/7 आपकी सहायता के लिए यहां हैं।',
    visitUs: 'हमसे मिलें',
    callUs: 'हमें कॉल करें',
    emailUs: 'हमें ईमेल करें',
    workingHours: 'कार्य समय',
    supportAvailable: '24/7 सहायता उपलब्ध',
    sendEnquiry: 'हमें एक पूछताछ भेजें',
    yourName: 'आपका नाम',
    enterName: 'अपना नाम दर्ज करें',
    phoneNumber: 'फोन नंबर',
    emailAddress: 'ईमेल पता',
    enterEmail: 'your@email.com',
    preferredDestination: 'पसंदीदा गंतव्य',
    selectDestination: 'गंतव्य चुनें',
    other: 'अन्य',
    yourMessage: 'आपका संदेश',
    tellTravelPlans: 'हमें अपनी यात्रा योजनाओं के बारे में बताएं...',
    sending: 'भेज रहा है...',
    sendEnquiryBtn: 'पूछताछ भेजें ✈️',
    enquirySuccess: '✅ आपकी पूछताछ के लिए धन्यवाद! हमारी टीम 24 घंटे के भीतर आपसे संपर्क करेगी।',
    enquiryFailed: '❌ पूछताछ सबमिट करने में विफल। कृपया पुनः प्रयास करें।',
    
    // Settings
    settings: 'सेटिंग्स',
    languageCurrency: 'भाषा और मुद्रा',
    language: 'भाषा',
    currency: 'मुद्रा',
    displaySettings: 'प्रदर्शन सेटिंग्स',
    theme: 'थीम',
    dark: 'डार्क',
    light: 'लाइट',
    auto: 'ऑटो (सिस्टम)',
    fontSize: 'फ़ॉन्ट आकार',
    small: 'छोटा',
    medium: 'मध्यम',
    large: 'बड़ा',
    showPrices: 'कीमतें दिखाएं',
    bookingLimitations: 'बुकिंग सीमाएं',
    maxGuests: 'प्रति बुकिंग अधिकतम मेहमान',
    advanceBooking: 'अग्रिम बुकिंग (दिन)',
    minNotice: 'न्यूनतम नोटिस (दिन)',
    searchPreferences: 'खोज प्राथमिकताएं',
    defaultSort: 'डिफ़ॉल्ट सॉर्ट',
    priceRangeMin: 'न्यूनतम मूल्य',
    priceRangeMax: 'अधिकतम मूल्य',
    showOnlyAvailable: 'केवल उपलब्ध टूर दिखाएं',
    notifications: 'सूचनाएं',
    emailNotifications: 'ईमेल सूचनाएं',
    smsNotifications: 'SMS सूचनाएं',
    promotionalEmails: 'प्रचार ईमेल',
    bookingReminders: 'बुकिंग रिमाइंडर',
    privacy: 'गोपनीयता',
    shareData: 'उपयोग डेटा साझा करें',
    locationAccess: 'स्थान पहुंच',
    resetDefaults: 'डिफ़ॉल्ट पर रीसेट करें',
    done: 'हो गया',
    settingsReset: 'सेटिंग्स डिफ़ॉल्ट पर रीसेट!',
  },
  ta: {
    // Navbar
    logout: 'வெளியேறு',
    guest: 'விருந்தினர்',

    // Hero
    heroSubtitle: 'நம்பிக்கையுடன் உலகத்தை ஆராயுங்கள்',
    heroTitle: 'உங்கள் அடுத்து கண்டறியுங்கள்',
    heroTitleGradient: 'சாகசம்',
    heroDescription: 'உலகின் மிகவும் அற்புதமான இலக்குகளுக்கான மறக்கமுடியாத சுற்றுலாக்களை முன்பதிவு செய்யுங்கள். தேர்ந்தெடுக்கப்பட்ட அனுபவங்கள், நிபுணர் வழிகாட்டிகள் மற்றும் நீடித்த நினைவுகள்.',
    exploreTours: 'சுற்றுலாக்கள் ஆய்வு',
    watchVideo: 'வீடியோவை பார்க்கவும்',
    destinations: 'இலக்குகள்',
    happyTravelers: 'மகிழ்ச்சியான பயணிகள்',
    averageRating: 'சராசரி மதிப்பீடு',

    // Features
    whyChooseUs: 'எங்களை ஏன் தேர்ந்தெடுக்க வேண்டும்',
    featuresTitle: 'சரியான பயணத்திற்கு தேவையான அனைத்து விஷயங்களும்',
    featuresSubtitle: 'உங்கள் பயணத்தை சீராகவும் நினைவுகூரக்கூடியதாகவும் மாற்ற நாங்கள் முழுமையான பயண தீர்வுகளை வழங்குகிறோம்',
    curatedExperiences: 'தேர்ந்தெடுக்கப்பட்ட அனுபவங்கள்',
    curatedDesc: 'மறக்க முடியாத அனுபவங்களுக்கு பயண நிபுணர்களால் தேர்ந்தெடுக்கப்பட்ட சுற்றுலாக்கள்.',
    bestPrice: 'சிறந்த விலை உத்தரவு',
    bestPriceDesc: 'எங்கள் விலை ஒப்பீட்டு உத்தரவின் மூலம் சிறந்த சலுகைகள் பெறுங்கள்.',
    secureBooking: 'பாதுகாப்பான முன்பதிவு',
    secureBookingDesc: 'எங்கள் பாதுகாப்பான கட்டண அமைப்பு மற்றும் உடனடி உறுதிப்படுத்தலுடன் நம்பிக்கையுடன் முன்பதிவு செய்யுங்கள்.',
    support247: '24/7 ஆதரவு',
    supportDesc: 'பயணத்துக்கு முன்பு, பயணத்தின் போது மற்றும் பிறகு எங்கள் குழு எப்போதும் உங்களுக்கு உதவ தயாராக உள்ளது.',

    // Tours Section
    popularTours: 'பிரபல சுற்றுலாக்கள்',
    exploreBest: 'எங்கள் சிறந்த இலக்குகளை ஆய்வு செய்யவும்',
    handPicked: 'உலகின் மிக அற்புதமான இடங்களுக்கு கையால் தேர்ந்தெடுக்கப்பட்ட சுற்றுலாக்கள்',
    searchPlaceholder: 'பெயர் அல்லது இடம் மூலம் சுற்றுலாக்களை தேடவும்...',
    allTours: 'அனைத்து சுற்றுலாக்கள்',
    priceLowToHigh: 'விலை: குறைந்தது அதிகம்',
    priceHighToLow: 'விலை: அதிகம் முதல் குறைவாக',
    highestRated: 'அதிக மதிப்பிடப்பட்டவை',
    duration: 'காலம்',
    noResults: 'சுற்றுலாக்கள் காணப்படவில்லை. வெவ்வேறு தேடலை முயற்சிக்கவும்.',
    seeMore: 'மேலும் சுற்றுலாக்கள் பார்க்க',
    seeLess: 'குறைவாக பார்க்க',

    // Tour Card
    from: 'இலிருந்து',
    max: 'அதிகபட்சம்',
    bookNow: 'இப்போது முன்பதிவு செய்யவும்',

    // Booking Modal
    book: 'முன்பதிவு',
    total: 'மொத்தம்',
    fullName: 'முழு பெயர்',
    email: 'மின்னஞ்சல்',
    phone: 'தொலைபேசி',
    tourDate: 'சுற்றுலா தேதி',
    numberOfGuests: 'விருந்தினர்கள் எண்ணிக்கை',
    confirmBooking: 'முன்பதிவை உறுதிசெய்',

    // Auth
    welcomeBack: 'மீட்டுமறிய வரவேற்பு',
    signInContinue: 'உங்கள் பயணத்தை தொடர உள்நுழையவும்',
    password: 'கடவுச்சொல்',
    signIn: 'உள்நுழைய',
    dontHaveAccount: 'கணக்கு இல்லை?',
    signUp: 'பதிவு செய்',
    joinTourExplorer: 'Tour Explorer இல் இணைக்கவும்',
    createAccount: 'உங்கள் அனுபவத்தை தொடங்க ஒரு கணக்கைப் பதிவு செய்யவும்',
    confirmPassword: 'கடவுச்சொல்லை உறுதிசெய்',
    alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    createAccountBtn: 'கணக்கை உருவாக்கவும்',

    // Messages
    loginRequired: 'ஒரு சுற்றுலாவை முன்பதிவு செய்ய தயவு செய்து உள்நுழைக',
    bookingConfirmed: 'முன்பதிவு உறுதியாகியது!',
    bookingFailed: 'முன்பதிவு தோல்வியடைந்தது. தயவு செய்து மீண்டும் முயற்சிக்கவும்.',
    loadingTours: 'அற்புத சுற்றுலாக்களை ஏற்றுகிறது...',
    failedToLoad: 'சுற்றுலாக்களை ஏற்றுவதில் தோல்வி. பின்னர் முயற்சிக்கவும்.',
    retry: 'மீண்டும் முயற்சிக்கவும்',
    // Navbar / common
    home: 'முகப்பு',
    categoriesNav: 'வகைகள்',
    toursNav: 'சுற்றுலாக்கள்',
    aboutNav: 'பற்றி',
    contactNav: 'தொடர்பு',
    brandName: 'Tour Explorer',
    brandTagline: 'உங்கள் பயணத் துணை',
    phoneContact: '📞 +91 90809 01058',
    quickLinks: 'முறுகு இணைப்புகள்',
    popularDestinationsTitle: 'பிரபல இலக்குகள்',
    contactInfoTitle: 'தொடர்பு தகவல்',
  },
  es: {
    logout: 'Cerrar sesión',
    guest: 'Invitado',
    heroSubtitle: 'Explora el mundo con confianza',
    heroTitle: 'Descubre tu próximo',
    heroTitleGradient: 'Aventura',
    heroDescription: 'Reserva tours inolvidables a los destinos más asombrosos del mundo. Experiencias seleccionadas, guías expertos y recuerdos para siempre.',
    exploreTours: 'Explorar Tours',
    watchVideo: 'Ver video',
    destinations: 'Destinos',
    happyTravelers: 'Viajeros felices',
    averageRating: 'Calificación promedio',
    whyChooseUs: 'Por qué elegirnos',
    featuresTitle: 'Todo lo que necesitas para el viaje perfecto',
    featuresSubtitle: 'Ofrecemos soluciones de viaje integrales para hacer tu viaje fluido e inolvidable',
    curatedExperiences: 'Experiencias seleccionadas',
    curatedDesc: 'Tours seleccionados por expertos en viajes para aventuras inolvidables.',
    bestPrice: 'Garantía del mejor precio',
    bestPriceDesc: 'Obtén las mejores ofertas con nuestra garantía de igualación de precios y ofertas exclusivas.',
    secureBooking: 'Reserva segura',
    secureBookingDesc: 'Reserva con confianza usando nuestro sistema de pago seguro y confirmación instantánea.',
    support247: 'Soporte 24/7',
    supportDesc: 'Nuestro equipo dedicado siempre está aquí para ayudarte antes, durante y después de tu viaje.',
    popularTours: 'Tours populares',
    exploreBest: 'Explora nuestros mejores destinos',
    handPicked: 'Tours seleccionados a mano a los lugares más increíbles del mundo',
    searchPlaceholder: 'Buscar tours por nombre o ubicación...',
    allTours: 'Todos los tours',
    priceLowToHigh: 'Precio: de menor a mayor',
    priceHighToLow: 'Precio: de mayor a menor',
    highestRated: 'Mejor valorados',
    duration: 'Duración',
    noResults: 'No se encontraron tours. Intenta otra búsqueda.',
    seeMore: 'Ver más tours',
    seeLess: 'Ver menos',
    from: 'Desde',
    max: 'Máx',
    bookNow: 'Reservar ahora',
    book: 'Reservar',
    total: 'Total',
    fullName: 'Nombre completo',
    email: 'Correo electrónico',
    phone: 'Teléfono',
    tourDate: 'Fecha del tour',
    numberOfGuests: 'Número de invitados',
    confirmBooking: 'Confirmar reserva',
    welcomeBack: 'Bienvenido de nuevo',
    signInContinue: 'Inicia sesión para continuar tu viaje',
    password: 'Contraseña',
    signIn: 'Iniciar sesión',
    dontHaveAccount: '¿No tienes una cuenta?',
    signUp: 'Regístrate',
    joinTourExplorer: 'Únete a Tour Explorer',
    createAccount: 'Crea una cuenta para comenzar tu aventura',
    confirmPassword: 'Confirmar contraseña',
    alreadyHaveAccount: '¿Ya tienes una cuenta?',
    createAccountBtn: 'Crear cuenta',
    loginRequired: 'Por favor inicia sesión para reservar un tour',
    bookingConfirmed: '¡Reserva confirmada!',
    bookingFailed: 'Error al crear la reserva. Intenta de nuevo.',
    loadingTours: 'Cargando tours increíbles...',
    failedToLoad: 'Error al cargar tours. Intenta más tarde.',
    retry: 'Reintentar',
    home: 'Inicio',
    categoriesNav: 'Categorías',
    toursNav: 'Tours',
    aboutNav: 'Acerca',
    contactNav: 'Contacto',
    brandName: 'Tour Explorer',
    brandTagline: 'Tu socio de viajes',
    phoneContact: '📞 +91 90809 01058',
    quickLinks: 'Enlaces rápidos',
    popularDestinationsTitle: 'Destinos populares',
    contactInfoTitle: 'Información de contacto',
  },
  fr: {
    logout: "Se déconnecter",
    guest: "Invité",
    heroSubtitle: "Explorez le monde en toute confiance",
    heroTitle: "Découvrez votre prochain",
    heroTitleGradient: "Aventure",
    heroDescription: "Réservez des circuits inoubliables vers les destinations les plus incroyables du monde. Expériences sélectionnées, guides experts et souvenirs durables.",
    exploreTours: "Explorer les tours",
    watchVideo: "Regarder la vidéo",
    destinations: "Destinations",
    happyTravelers: "Voyageurs heureux",
    averageRating: "Note moyenne",
    whyChooseUs: "Pourquoi nous choisir",
    featuresTitle: "Tout ce dont vous avez besoin pour le voyage parfait",
    featuresSubtitle: "Nous fournissons des solutions de voyage complètes pour rendre votre voyage fluide et mémorable",
    curatedExperiences: "Expériences sélectionnées",
    curatedDesc: "Tours triés sur le volet par des experts du voyage pour des aventures inoubliables.",
    bestPrice: "Garantie du meilleur prix",
    bestPriceDesc: "Obtenez les meilleures offres avec notre garantie d'égalité des prix et des offres exclusives.",
    secureBooking: "Réservation sécurisée",
    secureBookingDesc: "Réservez en toute confiance grâce à notre système de paiement sécurisé et à la confirmation instantanée.",
    support247: "Support 24/7",
    supportDesc: "Notre équipe dévouée est toujours là pour vous aider avant, pendant et après votre voyage.",
    popularTours: "Tours populaires",
    exploreBest: "Découvrez nos meilleures destinations",
    handPicked: "Tours sélectionnés à la main vers les endroits les plus incroyables du monde",
    searchPlaceholder: "Recherchez des tours par nom ou emplacement...",
    allTours: "Tous les tours",
    priceLowToHigh: "Prix : du plus bas au plus élevé",
    priceHighToLow: "Prix : du plus élevé au plus bas",
    highestRated: "Les mieux notés",
    duration: "Durée",
    noResults: "Aucun tour trouvé. Essayez une autre recherche.",
    seeMore: "Voir plus de tours",
    seeLess: "Voir moins",
    from: "Depuis",
    max: "Max",
    bookNow: "Réserver maintenant",
    book: "Réserver",
    total: "Total",
    fullName: "Nom complet",
    email: "E-mail",
    phone: "Téléphone",
    tourDate: "Date du tour",
    numberOfGuests: "Nombre d'invités",
    confirmBooking: "Confirmer la réservation",
    welcomeBack: "Bon retour",
    signInContinue: "Connectez-vous pour continuer votre voyage",
    password: "Mot de passe",
    signIn: "Se connecter",
    dontHaveAccount: "Vous n'avez pas de compte ?",
    signUp: "S'inscrire",
    joinTourExplorer: "Rejoignez Tour Explorer",
    createAccount: "Créez un compte pour commencer votre aventure",
    confirmPassword: "Confirmer le mot de passe",
    alreadyHaveAccount: "Vous avez déjà un compte ?",
    createAccountBtn: "Créer un compte",
    loginRequired: "Veuillez vous connecter pour réserver une visite",
    bookingConfirmed: "Réservation confirmée !",
    bookingFailed: "Échec de la réservation. Veuillez réessayer.",
    loadingTours: "Chargement des tours incroyables...",
    failedToLoad: "Échec du chargement des tours. Veuillez réessayer plus tard.",
    retry: "Réessayer",
    home: "Accueil",
    categoriesNav: "Catégories",
    toursNav: "Tours",
    aboutNav: "À propos",
    contactNav: "Contact",
    brandName: "Tour Explorer",
    brandTagline: "Votre partenaire de voyage",
    phoneContact: "📞 +91 90809 01058",
    quickLinks: "Liens rapides",
    popularDestinationsTitle: "Destinations populaires",
    contactInfoTitle: "Informations de contact",
  },
  de: {
    logout: 'Abmelden',
    guest: 'Gast',
    heroSubtitle: 'Erkunden Sie die Welt mit Vertrauen',
    heroTitle: 'Entdecke dein Nächstes',
    heroTitleGradient: 'Abenteuer',
    heroDescription: 'Buche unvergessliche Touren zu den erstaunlichsten Reisezielen der Welt. Kuratierte Erlebnisse, Expertenführer und Erinnerungen, die für immer bleiben.',
    exploreTours: 'Touren erkunden',
    watchVideo: 'Video ansehen',
    destinations: 'Ziele',
    happyTravelers: 'Glückliche Reisende',
    averageRating: 'Durchschnittsbewertung',
    whyChooseUs: 'Warum uns wählen',
    featuresTitle: 'Alles, was Sie für die perfekte Reise benötigen',
    featuresSubtitle: 'Wir bieten umfassende Reisepakete, damit Ihre Reise reibungslos und unvergesslich wird',
    curatedExperiences: 'Kuratierte Erlebnisse',
    curatedDesc: 'Von Reiseexperten ausgewählte Touren für unvergessliche Abenteuer.',
    bestPrice: 'Preisgarantie',
    bestPriceDesc: 'Erhalten Sie die besten Angebote mit unserer Preisgarantie und exklusiven Angeboten.',
    secureBooking: 'Sichere Buchung',
    secureBookingDesc: 'Buchen Sie mit Vertrauen über unser sicheres Zahlungssystem und sofortige Bestätigung.',
    support247: 'Support 24/7',
    supportDesc: 'Unser engagiertes Team ist immer da, um Ihnen vor, während und nach Ihrer Reise zu helfen.',
    popularTours: 'Beliebte Touren',
    exploreBest: 'Entdecken Sie unsere besten Reiseziele',
    handPicked: 'Handverlesene Touren zu den unglaublichsten Orten der Welt',
    searchPlaceholder: 'Touren nach Name oder Ort suchen...',
    allTours: 'Alle Touren',
    priceLowToHigh: 'Preis: aufsteigend',
    priceHighToLow: 'Preis: absteigend',
    highestRated: 'Am besten bewertet',
    duration: 'Dauer',
    noResults: 'Keine Touren gefunden. Versuchen Sie eine andere Suche.',
    seeMore: 'Mehr Touren anzeigen',
    seeLess: 'Weniger anzeigen',
    from: 'Ab',
    max: 'Max',
    bookNow: 'Jetzt buchen',
    book: 'Buchen',
    total: 'Gesamt',
    fullName: 'Vollständiger Name',
    email: 'E-Mail',
    phone: 'Telefon',
    tourDate: 'Tourdatum',
    numberOfGuests: 'Anzahl der Gäste',
    confirmBooking: 'Buchung bestätigen',
    welcomeBack: 'Willkommen zurück',
    signInContinue: 'Melden Sie sich an, um Ihre Reise fortzusetzen',
    password: 'Passwort',
    signIn: 'Anmelden',
    dontHaveAccount: 'Kein Konto?',
    signUp: 'Registrieren',
    joinTourExplorer: 'Treten Sie Tour Explorer bei',
    createAccount: 'Erstellen Sie ein Konto, um Ihr Abenteuer zu beginnen',
    confirmPassword: 'Passwort bestätigen',
    alreadyHaveAccount: 'Haben Sie bereits ein Konto?',
    createAccountBtn: 'Konto erstellen',
    loginRequired: 'Bitte melden Sie sich an, um eine Tour zu buchen',
    bookingConfirmed: 'Buchung bestätigt!',
    bookingFailed: 'Fehler beim Erstellen der Buchung. Bitte versuchen Sie es erneut.',
    loadingTours: 'Lade erstaunliche Touren...',
    failedToLoad: 'Fehler beim Laden der Touren. Bitte versuchen Sie es später erneut.',
    retry: 'Erneut versuchen',
    home: 'Startseite',
    categoriesNav: 'Kategorien',
    toursNav: 'Touren',
    aboutNav: 'Über',
    contactNav: 'Kontakt',
    brandName: 'Tour Explorer',
    brandTagline: 'Ihr Reisepartner',
    phoneContact: '📞 +91 90809 01058',
    quickLinks: 'Schnellzugriff',
    popularDestinationsTitle: 'Beliebte Ziele',
    contactInfoTitle: 'Kontaktinformationen',
  },
  zh: {
    logout: '登出',
    guest: '访客',
    heroSubtitle: '自信地探索世界',
    heroTitle: '发现您的下一个',
    heroTitleGradient: '冒险',
    heroDescription: '预订难忘的旅行，前往世界上最令人惊叹的目的地。精心策划的体验、专业导游和永恒的回忆。',
    exploreTours: '探索行程',
    watchVideo: '观看视频',
    destinations: '目的地',
    happyTravelers: '快乐的旅行者',
    averageRating: '平均评分',
    whyChooseUs: '为什么选择我们',
    featuresTitle: '完美旅行所需的一切',
    featuresSubtitle: '我们提供全面的旅行解决方案，让您的旅程顺畅且难忘',
    curatedExperiences: '精选体验',
    curatedDesc: '由旅行专家精心挑选的行程，带来难忘的冒险。',
    bestPrice: '最低价保证',
    bestPriceDesc: '通过我们的价格匹配保证和独家优惠，获得最佳优惠。',
    secureBooking: '安全预订',
    secureBookingDesc: '使用我们的安全支付系统和即时确认，自信预订。',
    support247: '24/7 支持',
    supportDesc: '我们的专职团队随时准备在旅程前、旅程中和旅程后为您提供帮助。',
    popularTours: '热门行程',
    exploreBest: '探索我们的最佳目的地',
    handPicked: '手工挑选的世界上最令人惊叹的目的地行程',
    searchPlaceholder: '按名称或位置搜索行程...',
    allTours: '所有行程',
    priceLowToHigh: '价格：从低到高',
    priceHighToLow: '价格：从高到低',
    highestRated: '最高评分',
    duration: '时长',
    noResults: '未找到行程。请尝试其他搜索。',
    seeMore: '查看更多行程',
    seeLess: '收起',
    from: '起价',
    max: '最多',
    bookNow: '立即预订',
    book: '预订',
    total: '总计',
    fullName: '全名',
    email: '电子邮件',
    phone: '电话',
    tourDate: '行程日期',
    numberOfGuests: '游客人数',
    confirmBooking: '确认预订',
    welcomeBack: '欢迎回来',
    signInContinue: '登录以继续您的旅程',
    password: '密码',
    signIn: '登录',
    dontHaveAccount: '没有账户？',
    signUp: '注册',
    joinTourExplorer: '加入 Tour Explorer',
    createAccount: '创建帐户以开始您的冒险',
    confirmPassword: '确认密码',
    alreadyHaveAccount: '已经有账户？',
    createAccountBtn: '创建账户',
    loginRequired: '请登录以预订行程',
    bookingConfirmed: '预订已确认！',
    bookingFailed: '创建预订失败。请再试一次。',
    loadingTours: '正在加载精彩行程...',
    failedToLoad: '加载行程失败。请稍后再试。',
    retry: '重试',
    home: '首页',
    categoriesNav: '分类',
    toursNav: '行程',
    aboutNav: '关于',
    contactNav: '联系',
    brandName: 'Tour Explorer',
    brandTagline: '您的旅行伙伴',
    phoneContact: '📞 +91 90809 01058',
    quickLinks: '快速链接',
    popularDestinationsTitle: '热门目的地',
    contactInfoTitle: '联系信息',
  },
  ja: {
    logout: 'ログアウト',
    guest: 'ゲスト',
    heroSubtitle: '自信を持って世界を探検しよう',
    heroTitle: 'あなたの次を見つけよう',
    heroTitleGradient: '冒険',
    heroDescription: '世界で最も素晴らしい目的地への忘れられないツアーを予約しましょう。厳選された体験、専門ガイド、そして永遠に残る思い出。',
    exploreTours: 'ツアーを探す',
    watchVideo: 'ビデオを見る',
    destinations: '目的地',
    happyTravelers: '満足した旅行者',
    averageRating: '平均評価',
    whyChooseUs: 'なぜ私たちを選ぶのか',
    featuresTitle: '完璧な旅のために必要なすべて',
    featuresSubtitle: '旅行をスムーズで思い出深いものにするための包括的な旅行ソリューションを提供します',
    curatedExperiences: '厳選された体験',
    curatedDesc: '忘れられない冒険のために旅行の専門家が設計した厳選ツアー。',
    bestPrice: 'ベストプライス保証',
    bestPriceDesc: '価格マッチ保証と独自の特典で最高のお得感を得ましょう。',
    secureBooking: '安全な予約',
    secureBookingDesc: '安全な支払いシステムと即時確認で安心して予約できます。',
    support247: '24/7 サポート',
    supportDesc: '専任チームが旅行の前、旅行中、旅行後にいつでもサポートします。',
    popularTours: '人気のツアー',
    exploreBest: '厳選最高の目的地を探検',
    handPicked: '世界で最も素晴らしい場所への厳選ツアー',
    searchPlaceholder: '名前または場所でツアーを検索...',
    allTours: 'すべてのツアー',
    priceLowToHigh: '価格：低→高',
    priceHighToLow: '価格：高→低',
    highestRated: '高評価',
    duration: '期間',
    noResults: 'ツアーが見つかりません。他の検索を試してください。',
    seeMore: 'もっとツアーを見る',
    seeLess: '閉じる',
    from: 'から',
    max: '最大',
    bookNow: '今すぐ予約',
    book: '予約',
    total: '合計',
    fullName: '氏名',
    email: 'メール',
    phone: '電話',
    tourDate: 'ツアー日',
    numberOfGuests: '参加者数',
    confirmBooking: '予約を確認',
    welcomeBack: 'お帰りなさい',
    signInContinue: '旅を続けるにはサインインしてください',
    password: 'パスワード',
    signIn: 'サインイン',
    dontHaveAccount: 'アカウントをお持ちでないですか？',
    signUp: 'サインアップ',
    joinTourExplorer: 'Tour Explorer に参加',
    createAccount: '冒険を始めるためにアカウントを作成',
    confirmPassword: 'パスワードを確認',
    alreadyHaveAccount: '既にアカウントをお持ちですか？',
    createAccountBtn: 'アカウント作成',
    loginRequired: 'ツアーを予約するにはログインしてください',
    bookingConfirmed: '予約が確認されました！',
    bookingFailed: '予約の作成に失敗しました。もう一度お試しください。',
    loadingTours: '素晴らしいツアーを読み込んでいます...',
    failedToLoad: 'ツアーの読み込みに失敗しました。後で再試行してください。',
    retry: '再試行',
    home: 'ホーム',
    categoriesNav: 'カテゴリ',
    toursNav: 'ツアー',
    aboutNav: '概要',
    contactNav: 'お問い合わせ',
    brandName: 'Tour Explorer',
    brandTagline: 'あなたの旅行パートナー',
    phoneContact: '📞 +91 90809 01058',
    quickLinks: 'クイックリンク',
    popularDestinationsTitle: '人気の目的地',
    contactInfoTitle: '連絡先情報',
  },
  ar: {
    logout: 'تسجيل الخروج',
    guest: 'زائر',
    heroSubtitle: 'استكشف العالم بثقة',
    heroTitle: 'اكتشف مغامرتك التالية',
    heroTitleGradient: 'مغامرة',
    heroDescription: 'احجز جولات لا تُنسى إلى أروع وجهات العالم. تجارب مُنسقة، مرشدون خبراء، وذكريات تدوم إلى الأبد.',
    exploreTours: 'استكشف الجولات',
    watchVideo: 'مشاهدة الفيديو',
    destinations: 'الوجهات',
    happyTravelers: 'مسافرون سعداء',
    averageRating: 'متوسط التقييم',
    whyChooseUs: 'لماذا تختارنا',
    featuresTitle: 'كل ما تحتاجه للرحلة المثالية',
    featuresSubtitle: 'نقدم حلول سفر شاملة لجعل رحلتك سلسة ولا تُنسى',
    curatedExperiences: 'تجارب مُنسقة',
    curatedDesc: 'جولات مُنتقاة يدويًا من قبل خبراء السفر لمغامرات لا تُنسى.',
    bestPrice: 'ضمان أفضل سعر',
    bestPriceDesc: 'احصل على أفضل العروض مع ضمان مطابقة الأسعار وعروض حصرية.',
    secureBooking: 'حجز آمن',
    secureBookingDesc: 'احجز بثقة باستخدام نظام الدفع الآمن والتأكيد الفوري.',
    support247: 'دعم 24/7',
    supportDesc: 'فريقنا المكرس هنا دائمًا لمساعدتك قبل وأثناء وبعد رحلتك.',
    popularTours: 'الجولات الشائعة',
    exploreBest: 'استكشف أفضل وجهاتنا',
    handPicked: 'جولات مُختارة يدويًا إلى أكثر الأماكن روعة في العالم',
    searchPlaceholder: 'ابحث عن الجولات بالاسم أو الموقع...',
    allTours: 'جميع الجولات',
    priceLowToHigh: 'السعر: من الأقل إلى الأعلى',
    priceHighToLow: 'السعر: من الأعلى إلى الأقل',
    highestRated: 'الأعلى تقييماً',
    duration: 'المدة',
    noResults: 'لم يتم العثور على جولات. حاول بحثًا آخر.',
    seeMore: 'عرض المزيد من الجولات',
    seeLess: 'عرض أقل',
    from: 'من',
    max: 'الحد الأقصى',
    bookNow: 'احجز الآن',
    book: 'حجز',
    total: 'المجموع',
    fullName: 'الاسم الكامل',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    tourDate: 'تاريخ الجولة',
    numberOfGuests: 'عدد الضيوف',
    confirmBooking: 'تأكيد الحجز',
    welcomeBack: 'مرحبًا بعودتك',
    signInContinue: 'قم بتسجيل الدخول لمتابعة رحلتك',
    password: 'كلمة المرور',
    signIn: 'تسجيل الدخول',
    dontHaveAccount: 'لا تملك حسابًا؟',
    signUp: 'إنشاء حساب',
    joinTourExplorer: 'انضم إلى Tour Explorer',
    createAccount: 'قم بإنشاء حساب لبدء مغامرتك',
    confirmPassword: 'تأكيد كلمة المرور',
    alreadyHaveAccount: 'هل لديك حساب بالفعل؟',
    createAccountBtn: 'إنشاء حساب',
    loginRequired: 'يرجى تسجيل الدخول لحجز جولة',
    bookingConfirmed: 'تم تأكيد الحجز!',
    bookingFailed: 'فشل إنشاء الحجز. حاول مرة أخرى.',
    loadingTours: 'جارٍ تحميل الجولات المذهلة...',
    failedToLoad: 'فشل تحميل الجولات. حاول مرة أخرى لاحقًا.',
    retry: 'أعد المحاولة',
    home: 'الصفحة الرئيسية',
    categoriesNav: 'التصنيفات',
    toursNav: 'الجولات',
    aboutNav: 'حول',
    contactNav: 'اتصل',
    brandName: 'Tour Explorer',
    brandTagline: 'شريك سفرك',
    phoneContact: '📞 +91 90809 01058',
    quickLinks: 'روابط سريعة',
    popularDestinationsTitle: 'الوجهات الشهيرة',
    contactInfoTitle: 'معلومات الاتصال',
  },
  ru: {
    logout: 'Выйти',
    guest: 'Гость',
    heroSubtitle: 'Исследуйте мир с уверенностью',
    heroTitle: 'Откройте для себя следующее',
    heroTitleGradient: 'Приключение',
    heroDescription: 'Бронируйте незабываемые туры в самые удивительные уголки мира. Курируемые впечатления, опытные гиды и воспоминания на всю жизнь.',
    exploreTours: 'Исследовать туры',
    watchVideo: 'Смотреть видео',
    destinations: 'Направления',
    happyTravelers: 'Счастливые путешественники',
    averageRating: 'Средний рейтинг',
    whyChooseUs: 'Почему выбирают нас',
    featuresTitle: 'Все, что нужно для идеального путешествия',
    featuresSubtitle: 'Мы предоставляем комплексные решения для путешествий, чтобы ваше путешествие было плавным и незабываемым',
    curatedExperiences: 'Отобранные впечатления',
    curatedDesc: 'Туры, отобранные экспертами, для незабываемых приключений.',
    bestPrice: 'Гарантия лучшей цены',
    bestPriceDesc: 'Получайте лучшие предложения с нашей гарантией совпадения цен и эксклюзивными предложениями.',
    secureBooking: 'Безопасное бронирование',
    secureBookingDesc: 'Бронируйте с уверенностью с нашей системой безопасных платежей и мгновенным подтверждением.',
    support247: 'Поддержка 24/7',
    supportDesc: 'Наша преданная команда всегда готова помочь вам до, во время и после вашей поездки.',
    popularTours: 'Популярные туры',
    exploreBest: 'Исследуйте наши лучшие направления',
    handPicked: 'Ручная подборка туров по самым невероятным местам мира',
    searchPlaceholder: 'Искать туры по названию или месту...',
    allTours: 'Все туры',
    priceLowToHigh: 'Цена: от низкой к высокой',
    priceHighToLow: 'Цена: от высокой к низкой',
    highestRated: 'Самые высоко оцененные',
    duration: 'Длительность',
    noResults: 'Туры не найдены. Попробуйте другой поиск.',
    seeMore: 'Показать больше туров',
    seeLess: 'Показать меньше',
    from: 'От',
    max: 'Макс',
    bookNow: 'Забронировать',
    book: 'Бронировать',
    total: 'Итого',
    fullName: 'Полное имя',
    email: 'Эл. почта',
    phone: 'Телефон',
    tourDate: 'Дата тура',
    numberOfGuests: 'Количество гостей',
    confirmBooking: 'Подтвердить бронирование',
    welcomeBack: 'С возвращением',
    signInContinue: 'Войдите, чтобы продолжить путешествие',
    password: 'Пароль',
    signIn: 'Войти',
    dontHaveAccount: 'Нет аккаунта?',
    signUp: 'Зарегистрироваться',
    joinTourExplorer: 'Присоединиться к Tour Explorer',
    createAccount: 'Создайте аккаунт, чтобы начать свое приключение',
    confirmPassword: 'Подтвердите пароль',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    createAccountBtn: 'Создать аккаунт',
    loginRequired: 'Пожалуйста, войдите, чтобы забронировать тур',
    bookingConfirmed: 'Бронирование подтверждено!',
    bookingFailed: 'Не удалось создать бронирование. Пожалуйста, попробуйте снова.',
    loadingTours: 'Загрузка удивительных туров...',
    failedToLoad: 'Не удалось загрузить туры. Пожалуйста, попробуйте позже.',
    retry: 'Повторить',
    home: 'Главная',
    categoriesNav: 'Категории',
    toursNav: 'Туры',
    aboutNav: 'О нас',
    contactNav: 'Контакты',
    brandName: 'Tour Explorer',
    brandTagline: 'Ваш партнер в путешествиях',
    phoneContact: '📞 +91 90809 01058',
    quickLinks: 'Быстрые ссылки',
    popularDestinationsTitle: 'Популярные направления',
    contactInfoTitle: 'Контактная информация',
  },
  pt: {
    logout: 'Sair',
    guest: 'Convidado',
    heroSubtitle: 'Explore o mundo com confiança',
    heroTitle: 'Descubra o seu próximo',
    heroTitleGradient: 'Aventura',
    heroDescription: 'Reserve tours inesquecíveis para os destinos mais incríveis do mundo. Experiências selecionadas, guias especializados e memórias para sempre.',
    exploreTours: 'Explorar tours',
    watchVideo: 'Assistir vídeo',
    destinations: 'Destinos',
    happyTravelers: 'Viajantes felizes',
    averageRating: 'Classificação média',
    whyChooseUs: 'Por que nos escolher',
    featuresTitle: 'Tudo o que você precisa para a viagem perfeita',
    featuresSubtitle: 'Fornecemos soluções completas de viagem para tornar sua jornada tranquila e memorável',
    curatedExperiences: 'Experiências selecionadas',
    curatedDesc: 'Tours selecionados por especialistas em viagens para aventuras inesquecíveis.',
    bestPrice: 'Garantia do melhor preço',
    bestPriceDesc: 'Obtenha as melhores ofertas com nossa garantia de preço e ofertas exclusivas.',
    secureBooking: 'Reserva segura',
    secureBookingDesc: 'Reserve com confiança usando nosso sistema de pagamento seguro e confirmação instantânea.',
    support247: 'Suporte 24/7',
    supportDesc: 'Nossa equipe dedicada está sempre aqui para ajudar antes, durante e depois da sua viagem.',
    popularTours: 'Tours populares',
    exploreBest: 'Explore nossos melhores destinos',
    handPicked: 'Tours selecionados à mão para os lugares mais incríveis do mundo',
    searchPlaceholder: 'Pesquisar tours por nome ou local...',
    allTours: 'Todos os tours',
    priceLowToHigh: 'Preço: do menor para o maior',
    priceHighToLow: 'Preço: do maior para o menor',
    highestRated: 'Mais bem avaliados',
    duration: 'Duração',
    noResults: 'Nenhum tour encontrado. Tente outra pesquisa.',
    seeMore: 'Ver mais tours',
    seeLess: 'Ver menos',
    from: 'A partir de',
    max: 'Máx',
    bookNow: 'Reservar agora',
    book: 'Reservar',
    total: 'Total',
    fullName: 'Nome completo',
    email: 'E-mail',
    phone: 'Telefone',
    tourDate: 'Data do tour',
    numberOfGuests: 'Número de convidados',
    confirmBooking: 'Confirmar reserva',
    welcomeBack: 'Bem-vindo de volta',
    signInContinue: 'Faça login para continuar sua viagem',
    password: 'Senha',
    signIn: 'Entrar',
    dontHaveAccount: 'Não possui uma conta?',
    signUp: 'Registrar',
    joinTourExplorer: 'Junte-se ao Tour Explorer',
    createAccount: 'Crie uma conta para começar sua aventura',
    confirmPassword: 'Confirmar senha',
    alreadyHaveAccount: 'Já possui uma conta?',
    createAccountBtn: 'Criar conta',
    loginRequired: 'Por favor, faça login para reservar um tour',
    bookingConfirmed: 'Reserva confirmada!',
    bookingFailed: 'Falha ao criar a reserva. Por favor, tente novamente.',
    loadingTours: 'Carregando tours incríveis...',
    failedToLoad: 'Falha ao carregar tours. Por favor, tente novamente mais tarde.',
    retry: 'Tentar novamente',
    home: 'Início',
    categoriesNav: 'Categorias',
    toursNav: 'Tours',
    aboutNav: 'Sobre',
    contactNav: 'Contato',
    brandName: 'Tour Explorer',
    brandTagline: 'Seu parceiro de viagem',
    phoneContact: '📞 +91 90809 01058',
    quickLinks: 'Links rápidos',
    popularDestinationsTitle: 'Destinos populares',
    contactInfoTitle: 'Informações de contato',
  },
  bn: {
    logout: 'প্রস্থান',
    guest: 'অতিথি',
    heroSubtitle: 'আত্মবিশ্বাসের সঙ্গে বিশ্ব আবিষ্কার করুন',
    heroTitle: 'আপনের পরবর্তী আবিষ্কার করুন',
    heroTitleGradient: 'অ্যাডভেঞ্চার',
    heroDescription: 'বিশ্বের সবচেয়ে চমৎকার গন্তব্যে অবিস্মরণীয় ট্যুর বুক করুন। নির্বাচিত অভিজ্ঞতা, দক্ষ গাইড এবং চিরস্থায়ী স্মৃতি।',
    exploreTours: 'ট্যুর অন্বেষণ করুন',
    watchVideo: 'ভিডিও দেখুন',
    destinations: 'গন্তব্য',
    happyTravelers: 'সন্তুষ্ট যাত্রীরা',
    averageRating: 'গড় রেটিং',
    whyChooseUs: 'কেন আমাদের নির্বাচন করবেন',
    featuresTitle: 'পরিপূর্ণ যাত্রার জন্য যা প্রয়োজন',
    featuresSubtitle: 'আপনার যাত্রাকে মসৃণ এবং স্মরণীয় করতে আমরা ব্যাপক ট্রাভেল সলিউশন সরবরাহ করি',
    curatedExperiences: 'নির্বাচিত অভিজ্ঞতা',
    curatedDesc: 'অবিস্মরণীয় অভিযানের জন্য ট্রাভেল বিশেষজ্ঞরা তৈরি করা বাছাইকৃত ট্যুর।',
    bestPrice: 'সেরা মূল্য গ্যারান্টি',
    bestPriceDesc: 'আমাদের মূল্য ম্যাচ গ্যারান্টি এবং বিশেষ অফারের মাধ্যমে সেরা ডিল পান।',
    secureBooking: 'নিরাপদ বুকিং',
    secureBookingDesc: 'আমাদের নিরাপদ পেমেন্ট সিস্টেম এবং তাৎক্ষণিক যাচাইকরণের মাধ্যমে আত্মবিশ্বাসের সাথে বুক করুন।',
    support247: '24/7 সাপোর্ট',
    supportDesc: 'আমাদের নিবেদিত দল আপনার ভ্রমণের আগে, সময় এবং পরে সর্বদা সাহায্য করতে প্রস্তুত।',
    popularTours: 'জনপ্রিয় ট্যুর',
    exploreBest: 'আমাদের সেরা গন্তব্যগুলি অন্বেষণ করুন',
    handPicked: 'বিশ্বের সবচেয়ে অবিশ্বাস্য স্থানগুলিতে হাতে বাছাই করা ট্যুর',
    searchPlaceholder: 'নাম বা অবস্থান দ্বারা ট্যুর অনুসন্ধান করুন...',
    allTours: 'সমস্ত ট্যুর',
    priceLowToHigh: 'মূল্য: কম থেকে বেশি',
    priceHighToLow: 'মূল্য: বেশি থেকে কম',
    highestRated: 'সর্বোচ্চ রেটেড',
    duration: 'সময়কাল',
    noResults: 'কোনো ট্যুর পাওয়া যায়নি। অন্য অনুসন্ধান চেষ্টা করুন।',
    seeMore: 'আরও ট্যুর দেখুন',
    seeLess: 'কম দেখুন',
    from: 'থেকে',
    max: 'সর্বোচ্চ',
    bookNow: 'এখনই বুক করুন',
    book: 'বুক',
    total: 'মোট',
    fullName: 'পুরো নাম',
    email: 'ইমেইল',
    phone: 'ফোন',
    tourDate: 'ট্যুরের তারিখ',
    numberOfGuests: 'অতিথির সংখ্যা',
    confirmBooking: 'বুকিং নিশ্চিত করুন',
    welcomeBack: 'স্বাগতম',
    signInContinue: 'আপনার যাত্রা চালিয়ে যেতে সাইন ইন করুন',
    password: 'পাসওয়ার্ড',
    signIn: 'সাইন ইন',
    dontHaveAccount: 'অ্যাকাউন্ট নেই?',
    signUp: 'সাইন আপ',
    joinTourExplorer: 'Tour Explorer এ যোগ দিন',
    createAccount: 'আপনার অ্যাডভেঞ্চার শুরু করতে একটি অ্যাকাউন্ট তৈরি করুন',
    confirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন',
    alreadyHaveAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    createAccountBtn: 'অ্যাকাউন্ট তৈরি করুন',
    loginRequired: 'একটি ট্যুর বুক করতে অনুগ্রহ করে লগইন করুন',
    bookingConfirmed: 'বুকিং নিশ্চিত হয়েছে!',
    bookingFailed: 'বুকিং তৈরি করতে ব্যর্থ। অনুগ্রহ করে আবার চেষ্টা করুন।',
    loadingTours: 'আশ্চর্যজনক ট্যুর লোড হচ্ছে...',
    failedToLoad: 'ট্যুর লোড করতে ব্যর্থ। অনুগ্রহ করে পরে আবার চেষ্টা করুন।',
    retry: 'পুনরায় চেষ্টা করুন',
    home: 'হোম',
    categoriesNav: 'বিভাগ',
    toursNav: 'ট্যুর',
    aboutNav: 'সম্পর্কে',
    contactNav: 'যোগাযোগ',
    brandName: 'Tour Explorer',
    brandTagline: 'আপনার ভ্রমণ সঙ্গী',
    phoneContact: '📞 +91 90809 01058',
    quickLinks: 'দ্রুত লিঙ্ক',
    popularDestinationsTitle: 'জনপ্রিয় গন্তব্য',
    contactInfoTitle: 'যোগাযোগের তথ্য',
    // New keys
    heroBadge: 'আপনার স্বপ্নের ছুটি অপেক্ষা করছে',
    heroMainTitle: 'বিশ্ব অন্বেষণ করুন',
    heroSearchPlaceholder: 'আপনি কোথায় যেতে চান? (যেমন, প্যারিস, বালি, দুবাই...)',
    searchBtn: 'অনুসন্ধান',
    popular: 'জনপ্রিয়',
    tourPackages: 'ট্যুর প্যাকেজ',
    rating: 'রেটিং',
    scrollToExplore: 'অন্বেষণ করতে স্ক্রোল করুন',
    browseByCategory: 'বিভাগ অনুসারে ব্রাউজ করুন',
    chooseTravelStyle: 'আপনার ভ্রমণ শৈলী চয়ন করুন',
    findPerfectPackage: 'আপনার ভ্রমণ পছন্দের সাথে মেলে এমন নিখুঁত ট্যুর প্যাকেজ খুঁজুন',
    packages: 'প্যাকেজ',
    catInternational: 'আন্তর্জাতিক ট্যুর',
    catInternationalDesc: 'বিশ্বব্যাপী গন্তব্য অন্বেষণ করুন',
    catDomestic: 'দেশীয় ট্যুর',
    catDomesticDesc: 'অবিশ্বাস্য ভারত আবিষ্কার করুন',
    catHoneymoon: 'হানিমুন প্যাকেজ',
    catHoneymoonDesc: 'দম্পতিদের জন্য রোমান্টিক গেটওয়ে',
    catAdventure: 'অ্যাডভেঞ্চার ট্যুর',
    catAdventureDesc: 'রোমাঞ্চকর অভিজ্ঞতা অপেক্ষা করছে',
    catBeach: 'বিচ হলিডে',
    catBeachDesc: 'সূর্য, বালি এবং সমুদ্র',
    catPilgrimage: 'তীর্থযাত্রা ট্যুর',
    catPilgrimageDesc: 'আধ্যাত্মিক যাত্রা',
    whyTourExplorer: 'কেন Tour Explorer',
    whyTravelWithUs: 'আমাদের সাথে কেন ভ্রমণ করবেন?',
    travelDreamsComeTrue: 'আমরা আমাদের ব্যতিক্রমী সেবার মাধ্যমে আপনার ভ্রমণ স্বপ্ন সত্যি করি',
    featBestPrice: 'সেরা মূল্য গ্যারান্টি',
    featBestPriceDesc: 'আমরা সমস্ত ট্যুর প্যাকেজে প্রতিযোগিতামূলক মূল্য এবং মূল্য মিলের গ্যারান্টি অফার করি।',
    featSafe: 'নিরাপদ ও সুরক্ষিত',
    featSafeDesc: 'আপনার নিরাপত্তা আমাদের অগ্রাধিকার। সমস্ত ট্যুর সম্পূর্ণ বীমাকৃত।',
    featHandpicked: 'হাতে বাছাই করা ট্যুর',
    featHandpickedDesc: 'প্রতিটি গন্তব্য আমাদের ভ্রমণ বিশেষজ্ঞদের দ্বারা সাবধানে নির্বাচিত।',
    featSupport: '24/7 সাপোর্ট',
    featSupportDesc: 'আপনার ট্রিপের আগে, সময় এবং পরে সার্বক্ষণিক গ্রাহক সহায়তা।',
    featEasyBooking: 'সহজ বুকিং',
    featEasyBookingDesc: 'তাৎক্ষণিক নিশ্চিতকরণ সহ সহজ এবং ঝামেলামুক্ত বুকিং প্রক্রিয়া।',
    featTrusted: 'বিশ্বস্ত রিভিউ',
    featTrustedDesc: '4.9 গড় রেটিং সহ 10,000+ সন্তুষ্ট ভ্রমণকারী।',
    testimonials: 'প্রশংসাপত্র',
    whatTravelersSay: 'আমাদের ভ্রমণকারীরা কী বলেন',
    testimonial1: 'অসাধারণ অভিজ্ঞতা! বালি ট্রিপ পুরোপুরি সংগঠিত ছিল।',
    testimonial2: 'সেরা ট্রাভেল এজেন্সি! মালদ্বীপে আমাদের হানিমুন স্বপ্ন সত্যি হয়েছে।',
    testimonial3: 'পেশাদার সেবা এবং অর্থের দুর্দান্ত মূল্য।',
    getInTouch: 'যোগাযোগ করুন',
    planDreamVacation: 'আপনার স্বপ্নের ছুটি পরিকল্পনা করুন',
    contactHelpText: 'প্রশ্ন আছে বা আপনার ট্রিপ পরিকল্পনায় সাহায্য দরকার? আমাদের ভ্রমণ বিশেষজ্ঞরা 24/7 আপনাকে সহায়তা করতে এখানে আছেন।',
    visitUs: 'আমাদের দেখুন',
    callUs: 'আমাদের কল করুন',
    emailUs: 'আমাদের ইমেইল করুন',
    workingHours: 'কাজের সময়',
    supportAvailable: '24/7 সাপোর্ট উপলব্ধ',
    sendEnquiry: 'আমাদের একটি অনুসন্ধান পাঠান',
    yourName: 'আপনার নাম',
    enterName: 'আপনার নাম লিখুন',
    phoneNumber: 'ফোন নম্বর',
    emailAddress: 'ইমেইল ঠিকানা',
    enterEmail: 'your@email.com',
    preferredDestination: 'পছন্দের গন্তব্য',
    selectDestination: 'গন্তব্য নির্বাচন করুন',
    other: 'অন্যান্য',
    yourMessage: 'আপনার বার্তা',
    tellTravelPlans: 'আপনার ভ্রমণ পরিকল্পনা সম্পর্কে বলুন...',
    sending: 'পাঠানো হচ্ছে...',
    sendEnquiryBtn: 'অনুসন্ধান পাঠান ✈️',
    enquirySuccess: '✅ আপনার অনুসন্ধানের জন্য ধন্যবাদ! আমাদের দল 24 ঘন্টার মধ্যে আপনার সাথে যোগাযোগ করবে।',
    enquiryFailed: '❌ অনুসন্ধান জমা দিতে ব্যর্থ। অনুগ্রহ করে আবার চেষ্টা করুন।',
    aboutThisTour: 'এই ট্যুর সম্পর্কে',
    highlights: 'হাইলাইটস',
  },
  // Urdu
  ur: {
    logout: 'لاگ آؤٹ',
    guest: 'مہمان',
    heroBadge: 'آپ کی خوابوں کی چھٹی منتظر ہے',
    heroMainTitle: 'دنیا کی سیر کریں',
    heroDescription: 'دنیا کی سب سے حیرت انگیز منزلوں کے لیے ناقابل فراموش ٹور بک کریں۔',
    heroSearchPlaceholder: 'آپ کہاں جانا چاہتے ہیں؟',
    searchBtn: 'تلاش کریں',
    popular: 'مقبول',
    tourPackages: 'ٹور پیکجز',
    destinations: 'منزلیں',
    happyTravelers: 'خوش مسافر',
    rating: 'درجہ بندی',
    scrollToExplore: 'دریافت کرنے کے لیے سکرول کریں',
    browseByCategory: 'زمرے کے لحاظ سے براؤز کریں',
    chooseTravelStyle: 'اپنا سفری انداز منتخب کریں',
    findPerfectPackage: 'اپنی سفری ترجیحات سے مماثل بہترین ٹور پیکج تلاش کریں',
    packages: 'پیکجز',
    catInternational: 'بین الاقوامی ٹور',
    catInternationalDesc: 'دنیا بھر کی منزلیں دریافت کریں',
    catDomestic: 'ملکی ٹور',
    catDomesticDesc: 'ناقابل یقین بھارت دریافت کریں',
    catHoneymoon: 'ہنی مون پیکجز',
    catHoneymoonDesc: 'جوڑوں کے لیے رومانوی گیٹ وے',
    catAdventure: 'ایڈونچر ٹور',
    catAdventureDesc: 'سنسنی خیز تجربات منتظر ہیں',
    catBeach: 'بیچ چھٹیاں',
    catBeachDesc: 'دھوپ، ریت اور سمندر',
    catPilgrimage: 'زیارت ٹور',
    catPilgrimageDesc: 'روحانی سفر',
    home: 'ہوم',
    categoriesNav: 'زمرے',
    toursNav: 'ٹور',
    aboutNav: 'ہمارے بارے میں',
    contactNav: 'رابطہ',
    brandName: 'Tour Explorer',
    brandTagline: 'آپ کا سفری ساتھی',
    signIn: 'سائن ان',
    bookNow: 'ابھی بک کریں',
    from: 'سے',
    max: 'زیادہ سے زیادہ',
  },
  // Indonesian
  id: {
    logout: 'Keluar',
    guest: 'Tamu',
    heroBadge: 'Liburan Impian Anda Menanti',
    heroMainTitle: 'Jelajahi Dunia Dengan',
    heroDescription: 'Pesan tur tak terlupakan ke destinasi paling menakjubkan di dunia.',
    heroSearchPlaceholder: 'Ke mana Anda ingin pergi?',
    searchBtn: 'Cari',
    popular: 'Populer',
    tourPackages: 'Paket Tur',
    destinations: 'Destinasi',
    happyTravelers: 'Wisatawan Bahagia',
    rating: 'Rating',
    scrollToExplore: 'Gulir untuk menjelajah',
    browseByCategory: 'Jelajahi Berdasarkan Kategori',
    chooseTravelStyle: 'Pilih Gaya Perjalanan Anda',
    findPerfectPackage: 'Temukan paket tur sempurna yang sesuai dengan preferensi perjalanan Anda',
    packages: 'Paket',
    catInternational: 'Tur Internasional',
    catInternationalDesc: 'Jelajahi destinasi di seluruh dunia',
    catDomestic: 'Tur Domestik',
    catDomesticDesc: 'Temukan India yang luar biasa',
    catHoneymoon: 'Paket Bulan Madu',
    catHoneymoonDesc: 'Liburan romantis untuk pasangan',
    catAdventure: 'Tur Petualangan',
    catAdventureDesc: 'Pengalaman mendebarkan menanti',
    catBeach: 'Liburan Pantai',
    catBeachDesc: 'Matahari, pasir, dan laut',
    catPilgrimage: 'Tur Ziarah',
    catPilgrimageDesc: 'Perjalanan spiritual',
    home: 'Beranda',
    categoriesNav: 'Kategori',
    toursNav: 'Tur',
    aboutNav: 'Tentang',
    contactNav: 'Kontak',
    brandName: 'Tour Explorer',
    brandTagline: 'Mitra Perjalanan Anda',
    signIn: 'Masuk',
    bookNow: 'Pesan Sekarang',
    from: 'Dari',
    max: 'Maks',
  },
  // Telugu
  te: {
    logout: 'లాగ్ అవుట్',
    guest: 'అతిథి',
    heroBadge: 'మీ కలల సెలవు ఎదురుచూస్తోంది',
    heroMainTitle: 'ప్రపంచాన్ని అన్వేషించండి',
    heroDescription: 'ప్రపంచంలోని అత్యంత అద్భుతమైన గమ్యస్థానాలకు మరపురాని పర్యటనలను బుక్ చేయండి.',
    heroSearchPlaceholder: 'మీరు ఎక్కడికి వెళ్ళాలనుకుంటున్నారు?',
    searchBtn: 'వెతకండి',
    popular: 'ప్రసిద్ధ',
    tourPackages: 'టూర్ ప్యాకేజీలు',
    destinations: 'గమ్యస్థానాలు',
    happyTravelers: 'సంతోషకరమైన యాత్రికులు',
    rating: 'రేటింగ్',
    scrollToExplore: 'అన్వేషించడానికి స్క్రోల్ చేయండి',
    browseByCategory: 'వర్గం ద్వారా బ్రౌజ్ చేయండి',
    chooseTravelStyle: 'మీ ప్రయాణ శైలిని ఎంచుకోండి',
    findPerfectPackage: 'మీ ప్రయాణ ప్రాధాన్యతలకు సరిపోయే సరైన టూర్ ప్యాకేజీని కనుగొనండి',
    packages: 'ప్యాకేజీలు',
    catInternational: 'అంతర్జాతీయ టూర్లు',
    catInternationalDesc: 'ప్రపంచవ్యాప్తంగా గమ్యస్థానాలను అన్వేషించండి',
    catDomestic: 'దేశీయ టూర్లు',
    catDomesticDesc: 'అద్భుతమైన భారతదేశాన్ని కనుగొనండి',
    catHoneymoon: 'హనీమూన్ ప్యాకేజీలు',
    catHoneymoonDesc: 'జంటలకు రొమాంటిక్ గెటావేలు',
    catAdventure: 'అడ్వెంచర్ టూర్లు',
    catAdventureDesc: 'ఉత్తేజకరమైన అనుభవాలు ఎదురుచూస్తున్నాయి',
    catBeach: 'బీచ్ సెలవులు',
    catBeachDesc: 'ఎండ, ఇసుక మరియు సముద్రం',
    catPilgrimage: 'తీర్థయాత్ర టూర్లు',
    catPilgrimageDesc: 'ఆధ్యాత్మిక ప్రయాణాలు',
    home: 'హోమ్',
    categoriesNav: 'వర్గాలు',
    toursNav: 'టూర్లు',
    aboutNav: 'గురించి',
    contactNav: 'సంప్రదించండి',
    brandName: 'Tour Explorer',
    brandTagline: 'మీ ప్రయాణ భాగస్వామి',
    signIn: 'సైన్ ఇన్',
    bookNow: 'ఇప్పుడే బుక్ చేయండి',
    from: 'నుండి',
    max: 'గరిష్ట',
  },
  // Korean
  ko: {
    logout: '로그아웃',
    guest: '손님',
    heroBadge: '꿈의 휴가가 기다립니다',
    heroMainTitle: '세계를 탐험하세요',
    heroDescription: '세계에서 가장 놀라운 목적지로 잊을 수 없는 투어를 예약하세요.',
    heroSearchPlaceholder: '어디로 가고 싶으세요?',
    searchBtn: '검색',
    popular: '인기',
    tourPackages: '투어 패키지',
    destinations: '목적지',
    happyTravelers: '행복한 여행자',
    rating: '평점',
    scrollToExplore: '스크롤하여 탐색',
    browseByCategory: '카테고리별 찾아보기',
    chooseTravelStyle: '여행 스타일을 선택하세요',
    findPerfectPackage: '여행 취향에 맞는 완벽한 투어 패키지를 찾으세요',
    packages: '패키지',
    catInternational: '해외 투어',
    catInternationalDesc: '전 세계 목적지 탐험',
    catDomestic: '국내 투어',
    catDomesticDesc: '놀라운 인도 발견',
    catHoneymoon: '허니문 패키지',
    catHoneymoonDesc: '커플을 위한 로맨틱 여행',
    catAdventure: '어드벤처 투어',
    catAdventureDesc: '스릴 넘치는 경험이 기다립니다',
    catBeach: '비치 휴가',
    catBeachDesc: '태양, 모래, 바다',
    catPilgrimage: '성지순례 투어',
    catPilgrimageDesc: '영적 여행',
    home: '홈',
    categoriesNav: '카테고리',
    toursNav: '투어',
    aboutNav: '소개',
    contactNav: '연락처',
    brandName: 'Tour Explorer',
    brandTagline: '당신의 여행 파트너',
    signIn: '로그인',
    bookNow: '지금 예약',
    from: '부터',
    max: '최대',
  },
  // Italian
  it: {
    logout: 'Esci',
    guest: 'Ospite',
    heroBadge: 'La tua vacanza da sogno ti aspetta',
    heroMainTitle: 'Esplora il mondo con',
    heroDescription: 'Prenota tour indimenticabili verso le destinazioni più incredibili del mondo.',
    heroSearchPlaceholder: 'Dove vuoi andare?',
    searchBtn: 'Cerca',
    popular: 'Popolari',
    tourPackages: 'Pacchetti Tour',
    destinations: 'Destinazioni',
    happyTravelers: 'Viaggiatori Felici',
    rating: 'Valutazione',
    scrollToExplore: 'Scorri per esplorare',
    browseByCategory: 'Sfoglia per Categoria',
    chooseTravelStyle: 'Scegli il tuo stile di viaggio',
    findPerfectPackage: 'Trova il pacchetto tour perfetto che corrisponde alle tue preferenze di viaggio',
    packages: 'Pacchetti',
    catInternational: 'Tour Internazionali',
    catInternationalDesc: 'Esplora destinazioni in tutto il mondo',
    catDomestic: 'Tour Nazionali',
    catDomesticDesc: 'Scopri l\'incredibile India',
    catHoneymoon: 'Pacchetti Luna di Miele',
    catHoneymoonDesc: 'Fughe romantiche per coppie',
    catAdventure: 'Tour Avventura',
    catAdventureDesc: 'Esperienze emozionanti ti aspettano',
    catBeach: 'Vacanze al Mare',
    catBeachDesc: 'Sole, sabbia e mare',
    catPilgrimage: 'Tour Pellegrinaggio',
    catPilgrimageDesc: 'Viaggi spirituali',
    home: 'Home',
    categoriesNav: 'Categorie',
    toursNav: 'Tour',
    aboutNav: 'Chi siamo',
    contactNav: 'Contatti',
    brandName: 'Tour Explorer',
    brandTagline: 'Il tuo partner di viaggio',
    signIn: 'Accedi',
    bookNow: 'Prenota Ora',
    from: 'Da',
    max: 'Max',
  },
  // Dutch
  nl: {
    logout: 'Uitloggen',
    guest: 'Gast',
    heroBadge: 'Je droomvakantie wacht',
    heroMainTitle: 'Verken de wereld met',
    heroDescription: 'Boek onvergetelijke tours naar de meest verbazingwekkende bestemmingen ter wereld.',
    heroSearchPlaceholder: 'Waar wil je naartoe?',
    searchBtn: 'Zoeken',
    popular: 'Populair',
    tourPackages: 'Tourpakketten',
    destinations: 'Bestemmingen',
    happyTravelers: 'Tevreden Reizigers',
    rating: 'Beoordeling',
    scrollToExplore: 'Scroll om te verkennen',
    browseByCategory: 'Blader op Categorie',
    chooseTravelStyle: 'Kies je reisstijl',
    findPerfectPackage: 'Vind het perfecte tourpakket dat past bij je reisvoorkeuren',
    packages: 'Pakketten',
    catInternational: 'Internationale Tours',
    catInternationalDesc: 'Verken bestemmingen wereldwijd',
    catDomestic: 'Binnenlandse Tours',
    catDomesticDesc: 'Ontdek het ongelooflijke India',
    catHoneymoon: 'Huwelijksreispakketten',
    catHoneymoonDesc: 'Romantische uitjes voor koppels',
    catAdventure: 'Avontuurlijke Tours',
    catAdventureDesc: 'Spannende ervaringen wachten',
    catBeach: 'Strandvakanties',
    catBeachDesc: 'Zon, zand en zee',
    catPilgrimage: 'Pelgrimstochten',
    catPilgrimageDesc: 'Spirituele reizen',
    home: 'Home',
    categoriesNav: 'Categorieën',
    toursNav: 'Tours',
    aboutNav: 'Over ons',
    contactNav: 'Contact',
    brandName: 'Tour Explorer',
    brandTagline: 'Je reispartner',
    signIn: 'Inloggen',
    bookNow: 'Nu Boeken',
    from: 'Vanaf',
    max: 'Max',
  },
};

// Add additional language keys (fallback to English) so UI can switch to them immediately.
// These are placeholders — you can replace the values with proper translations later.
const extraLangCodes = ['es','fr','de','zh','ja','ar','ru','pt','bn','ur','id','ta','te','ko','it','nl'];
extraLangCodes.forEach(code => {
  if (!translations[code]) {
    // shallow copy of English translations so missing keys won't return bare keys
    translations[code] = { ...translations.en };
  }
});

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    try {
      return localStorage.getItem('language') || 'en';
    } catch (e) {
      return 'en';
    }
  });

  const [currency, setCurrencyState] = useState(() => {
    try {
      return localStorage.getItem('currency') || 'INR';
    } catch (e) {
      return 'INR';
    }
  });

  const t = (key) => {
    return translations[language] && translations[language][key]
      ? translations[language][key]
      : translations.en[key] || key;
  };

  const formatPrice = (price) => {
    // Exchange rates (approximate: base is USD)
    const rates = {
      USD: 1,
      INR: 83,
      EUR: 0.92,
      GBP: 0.79
    };
    
    const convertedPrice = Math.round(price * rates[currency]);
    
    switch (currency) {
      case 'INR':
        return `₹${convertedPrice.toLocaleString('en-IN')}`;
      case 'EUR':
        return `€${convertedPrice.toLocaleString('de-DE')}`;
      case 'GBP':
        return `£${convertedPrice.toLocaleString('en-GB')}`;
      case 'USD':
      default:
        return `$${price.toLocaleString('en-US')}`;
    }
  };

  // wrapped setters that persist selection
  const setLanguage = (lang) => {
    setLanguageState(lang);
    try { localStorage.setItem('language', lang); } catch (e) {}
    // set a sensible default currency for some languages
    const langCurrencyMap = {
      en: 'USD', hi: 'INR', bn: 'INR', ta: 'INR', te: 'INR', ur: 'INR',
      es: 'USD', fr: 'EUR', de: 'EUR', pt: 'EUR', it: 'EUR', nl: 'EUR',
      zh: 'USD', ja: 'USD', ko: 'USD', ru: 'USD', id: 'USD', ar: 'USD'
    };
    const suggested = langCurrencyMap[lang] || 'USD';
    setCurrencyState(suggested);
    try { localStorage.setItem('currency', suggested); } catch (e) {}
  };

  const setCurrency = (c) => {
    setCurrencyState(c);
    try { localStorage.setItem('currency', c); } catch (e) {}
  };

  const value = {
    language,
    setLanguage,
    currency,
    setCurrency,
    t,
    formatPrice,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};
